### ISSUE TITLE
Screenshots must show elementary OS default settings

### ISSUE THREAD

**Issue by danrabbit** [Timecraft/notifier#15]
I'm requesting changes on the latest release of Notifier for publication in AppCenter because it appears that the screenshots don't show elementary OS default settings: specifically with regard to window controls. Screenshots for apps in AppCenter must use default settings. Please update the screenshots and publish a new release :)

**Comment by Timecraft** [comment]
Oh woops! Didn't even realize that! Need to make a not to myself telling me to switch that back over to elementary. Love the OS, but I can't live without that minimize feature. Sorry about that! Will get right on it!
