### ISSUE TITLE
Consider a more elementary-styled icon

### ISSUE THREAD

**Issue by danrabbit** [Timecraft/notifier#16]
The current icon does not fit with [the composition](https://elementary.io/docs/human-interface-guidelines#iconography) of elementary icons at all. You might want to consider combining a couple icons from the system set to make your icon look a little more native: You can take the tile icon from `postscript-viewer` in apps and use the exclamation mark from `dialog-error` in status to pretty easily get something like the attachment:

![screenshot from 2018-04-22 13 05 09 2x](https://user-images.githubusercontent.com/7277719/39099318-cfbbf102-462d-11e8-8b90-3ed98b899703.png)

[com.github.timecraft.notifier.svg.zip](https://github.com/Timecraft/notifier/files/1936049/com.github.timecraft.notifier.svg.zip)

**Comment by Timecraft** [comment]
I was trying to find a way to get that light gradient, put couldnt figure it out. That's a great icon though! I'll definitely try out something like that! Thanks a lot Dan!

**Comment by Timecraft** [comment]
Is this maybe trying too hard? 
[com.github.timecraft.notifier.svg.zip](https://github.com/Timecraft/notifier/files/1936140/com.github.timecraft.notifier.svg.zip)

**Comment by cassidyjames** [comment]
Personally, I feel like the yellow plus the red are a little too harsh together. I'd say stick with one or the other. Dan's red icon is bright and attention-grabbing but also pretty simple, which I like.
