### ISSUE TITLE
Use Granite DatePicker

### ISSUE THREAD

**Issue by cassidyjames** [Timecraft/notifier#19]
Granite has a nice DatePicker widget which can be used instead of three SpinButtons: https://valadoc.org/granite/Granite.Widgets.DatePicker.html

**Comment by Timecraft** [comment]
Touching on both this and #20, attempting to compile anything with Granite returns `fatal error: granite.h: No such file or directory`. I have made sure that all libgranites are installed, as well as the elementary-sdk, yet it still returns this error. Not entirely sure what the issue is.

**Comment by cassidyjames** [comment]
You need to add Granite to your dependencies.

**Comment by Timecraft** [comment]
In the CMakeLists.txt? Already did that and ran `cmake ..`

**Comment by Timecraft** [comment]
I'm so sorry Mr. James, but I put the dependency in the wrong spot. It's all working just fine now. Thank you for your time!
