### ISSUE TITLE
App icon can't be found

### ISSUE THREAD

**Issue by danrabbit** [Timecraft/notifier#30]
See https://appstream.elementary.io/appcenter/html/bionic/main/issues/com.github.timecraft.notifier.html

From what I can tell it looks like you're using a shell script to install icons. Instead you should use Meson to install them. For your convenience, consider something like this:

https://github.com/danrabbit/lookbook/blob/master/data/meson.build#L1

Which names all the icons as things like `16.svg`, `24.svg` etc in the same directory

or

https://github.com/elementary/music/blob/master/data/meson.build#L1

which names all the icons more like how you already have it

**Comment by Timecraft** [comment]
The shell script is (was) actually for manual installs (see line 2). I'll be looking into this super closely right now! Thanks a lot!

**Comment by Timecraft** [comment]
Looks to me like I completely left out the installation of icons. Makes a lot of sense as to why the icon did not show up in my virtual machine.

**Comment by Timecraft** [comment]
Got it all fixed up in the latest commit. Will be releasing a new version posthaste! Thank you so much Mr. Foré!
