### ISSUE TITLE
Not saving frequency

### ISSUE THREAD

**Issue by CallieG** [Timecraft/notifier#31]
Hi, 

So, as the title suggests, no matter what I choose, the frequency of the notification is never properly applied.

**Comment by CallieG** [comment]
And now, with an addition of a new notification reminder, it seems as though frequency was correctly applied.

As usual, here's the dump:

`callie@ix:~$ com.github.timecraft.notifier
** Message: 11:36:08.000: notifier.vala:52: 11:36 AM
Unable to add TIMING column** Message: 11:36:08.002: notifier.vala:256: 2
** Message: 11:36:49.319: notifier.vala:1177: date.length 3

** Message: 11:36:49.320: notifier.vala:1193: iNovi
** Message: 11:36:49.320: notifier.vala:1193: i16i
** Message: 11:36:49.320: notifier.vala:1193: i2018i

** Message: 11:36:49.320: notifier.vala:1202: Changing month into computer friendly number.

** Message: 11:36:49.320: notifier.vala:1221: Year 2018
** Message: 11:36:49.320: notifier.vala:1222: Month Nov
** Message: 11:36:49.320: notifier.vala:1223: Day 16
** Message: 11:36:49.320: notifier.vala:1224: Hour 11
** Message: 11:36:49.320: notifier.vala:1225: Min 45 AM

** Message: 11:36:49.320: notifier.vala:1230: Adding reminder to main window.
** Message: 11:36:49.322: notifier.vala:1244: Preparing for database!
** Message: 11:36:49.322: notifier.vala:1276: Saving...
** Message: 11:36:49.331: notifier.vala:1329: SAVED

(com.github.timecraft.notifier:2783): Gtk-WARNING **: 11:36:49.343: Attempting to add a widget with type GtkGrid to a container of type GtkApplicationWindow, but the widget is already inside a container of type GtkApplicationWindow, please remove the widget from its existing container first.
`

**Comment by CallieG** [comment]
So, I don't know if this means it isn't a bug, but it seems to work okay now, after a reboot.

**Comment by Timecraft** [comment]
Hmm. That is strange. I'll look in my VM to see if this is a bug. Thank you for this!

**Comment by Timecraft** [comment]
There may be issues with the daemon (handles notification sending) while having the app open. It seems that the database is not very happy with having multiple things trying to access it at once. I have some more testing to do, but see if it will send after closing the application. If it doesn't, I think I can figure out something that'll make it work.

**Comment by Timecraft** [comment]
Whoops! Sent that to the wrong issue. I'm a professional, I swear

**Comment by Timecraft** [comment]
Yeah, I'm not having that issue. Keep on trying it, and see if that problem persists
