### ISSUE TITLE
Not showing any notifications.

### ISSUE THREAD

**Issue by CallieG** [Timecraft/notifier#32]

**Comment by CallieG** [comment]
Just installed, and I cannot seem to get the application to show any notifications.  I have looked in all of the places I would need to look, and have thus far had no success.

**Comment by CallieG** [comment]
So far, so good.  I just added a new notification reminder, and it actually did show up in the frequency columns.   

Now, to see if it actually notifies me.

Here's a dump:

`callie@ix:~$ com.github.timecraft.notifier
** Message: 11:36:08.000: notifier.vala:52: 11:36 AM
Unable to add TIMING column** Message: 11:36:08.002: notifier.vala:256: 2
** Message: 11:36:49.319: notifier.vala:1177: date.length 3

** Message: 11:36:49.320: notifier.vala:1193: iNovi
** Message: 11:36:49.320: notifier.vala:1193: i16i
** Message: 11:36:49.320: notifier.vala:1193: i2018i

** Message: 11:36:49.320: notifier.vala:1202: Changing month into computer friendly number.

** Message: 11:36:49.320: notifier.vala:1221: Year 2018
** Message: 11:36:49.320: notifier.vala:1222: Month Nov
** Message: 11:36:49.320: notifier.vala:1223: Day 16
** Message: 11:36:49.320: notifier.vala:1224: Hour 11
** Message: 11:36:49.320: notifier.vala:1225: Min 45 AM

** Message: 11:36:49.320: notifier.vala:1230: Adding reminder to main window.
** Message: 11:36:49.322: notifier.vala:1244: Preparing for database!
** Message: 11:36:49.322: notifier.vala:1276: Saving...
** Message: 11:36:49.331: notifier.vala:1329: SAVED

(com.github.timecraft.notifier:2783): Gtk-WARNING **: 11:36:49.343: Attempting to add a widget with type GtkGrid to a container of type GtkApplicationWindow, but the widget is already inside a container of type GtkApplicationWindow, please remove the widget from its existing container first.
`

**Comment by Timecraft** [comment]
I'll look into this as soon as I can. Thank you for the report!

**Comment by Timecraft** [comment]
There may be issues with the daemon (handles notification sending) while having the app open. It seems that the database is not very happy with having multiple things trying to access it at once. I have some more testing to do, but see if it will send after closing the application. If it doesn't, I think I can figure out something that'll make it work.
