### ISSUE TITLE
Reminder is not preserved

### ISSUE THREAD

**Issue by Gabriel-p** [Timecraft/notifier#35]
After restarting the system, the reminder is gone.

**Comment by Timecraft** [comment]
I really hope that I don't sound patronizing or dismissive when I say this, but are you properly saving the reminder? I just tested it out on my machine (any person's least favorite saying) and it worked fine. Created, saved, exited, rebooted, and relaunched Notifier. It was still there.

This is with the same build available in the AppCenter

**Comment by Gabriel-p** [comment]
I am, but the app is actually riddled with bugs. Hours set are changed, have to open twice to load stored reminders (first time shows an empty app), check marks apparently do nothing, ...

This needs a few weeks of developing, it's not even beta. Perhaps I'll try it again later on. Cheers.
